CoreCLR: Add missing null guard (#126704)
This fixes Release builds using GCC.

Without this patch, these builds fail with:

```
  /home/runner/dotnet-runtime/src/coreclr/gc/unix/cgroup.cpp:518:21: error: '%s' directive argument is null [-Werror=format-overflow=]
    518 |         if (asprintf(&mem_usage_filename, "%s%s", s_memory_cgroup_path, filename) < 0)
        |             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Part of https://github.com/dotnet/runtime/issues/55803.